version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: bloom-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bloom
      MONGO_INITDB_ROOT_PASSWORD: bloom-dev-password
      MONGO_INITDB_DATABASE: bloom-auth
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - bloom-network

  redis:
    image: redis:7-alpine
    container_name: bloom-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bloom-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  bloom-network:
    driver: bridge